version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - APP_ENV=development 