services:
  # Backend API Service
  - type: web
    name: arxiv-mastery-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      # Consulting System Environment Variables
      - key: ZOOM_API_KEY
        sync: false
      - key: ZOOM_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: ROCKETREACH_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true 